### ISSUE TITLE
Incoming transfer request creates outgoing

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#11]
When creating an incoming transfer the backend creates an outgoing.
See the screenshots for request and response.

**Request:**
![bildschirmfoto 2017-03-03 um 16 29 47](https://cloud.githubusercontent.com/assets/1683147/23557031/e3acf63e-002e-11e7-9e85-ae32726207ee.png)

**Response:**
![bildschirmfoto 2017-03-03 um 16 29 54](https://cloud.githubusercontent.com/assets/1683147/23557047/f203c910-002e-11e7-9858-0ef2b0a12e7f.png)

**Comment by rweisse** [comment]
fixed ;-)
