### ISSUE TITLE
CORS issue?!

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#16]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.iltis.hftl.club/event/8/transfers/storage/count. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). (unbekannt)
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.  jquery.min.js:2:40212
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.iltis.hftl.club/event/9/transfers/storage/count. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). (unbekannt)
POST 
XHR 
https://api.iltis.hftl.club/event/9/transfers/storage/count [HTTP/1.1 502 Proxy Error 199ms]

[12:22] 
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.iltis.hftl.club/event/9/transfers/storage/count. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

[12:22] 
kommt bei jedem klick auf den button

[12:22] 
"speichern"

**Comment by rweisse** [comment]
Closed. Error produced by inconsistent DB entry.
