### ISSUE TITLE
Factories should create real date objects

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#2]
In all factories, instead of

`if (obj.datetime) event.datetime = obj.datetime;`

use 

`if (obj.datetime) event.datetime = new Date(obj.datetime);`

**Comment by rweisse** [comment]
I have already fixed that ;-)

**Comment by fmalcher** [comment]
ah right, you should try to use more atomic commits for such things ;-)

**Comment by fmalcher** [comment]
done in https://github.com/hftlclub/node-iltis/commit/fa1a75ee40dc667f7496a4e90f3873db743732da
