### ISSUE TITLE
Database reset

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#29]
- additional table for settings (?) as key/value store (maybe we can use it for something else later, so keep it generic)
- Flag `resettable = true`
- REST endpoint `/reset` that resets the DB with sample values

**Comment by fmalcher** [comment]
I'd rather like to see a more "speaking" word here than `devMode`.

1.) Imagine, the dev mode enables some more dev features – we can't disable the database reset then because it's hidden in the `devMode` feature.

2.) `devMode` does not explicitly claim that a database reset is actually allowed – it could mean anything from performance stuff over debugging features up to missing build optimization. A more specific verb would be less ambiguous here. I suggest `resettable` or `databaseResetAllowed`.

@rweisse

**Comment by rweisse** [comment]
See #35
