### ISSUE TITLE
Max Mustermann

### ISSUE THREAD

**Issue by ulbricht-inr** [hftlclub/node-iltis#32]
right upper corner shows "Max Mustermann" but not me....

**Comment by fmalcher** [comment]
Yep, thanks ;-) That's still TODO and just a placeholder.
However, this is the wrong repo 😜

Frontend: https://github.com/hftlclub/ng-iltis
Backend: https://github.com/hftlclub/node-iltis


I will close this by now and merge it into the right issue.
