### ISSUE TITLE
management: Validation for numbers

### ISSUE THREAD

**Issue by ulbricht-inr** [hftlclub/node-iltis#34]
don't know what the effect will be but it can't be good :dagger: 
the same for "kastengrößen" :P

**Comment by fmalcher** [comment]
TODO:
Validate numbers in the backend

- SizeType.amount
- CrateType.slots

@rweisse

**Comment by fmalcher** [comment]
Same for the frontend which will be tracked in https://github.com/hftlclub/ng-iltis/issues/67
