### ISSUE TITLE
Deletable check (units, categories, cratetypes) for active products

### ISSUE THREAD

**Issue by rweisse** [hftlclub/node-iltis#41]
- Block deletion for units and categories if they are referenced by active products (frontend + backend)
   + additionally add unitCount to unit model. (backend)
- CrateTypes can be deleted even if they are used. But the user should be warned, because they will be deleted by cascade. The warning will rise if cratetypeCount is higher than 0 (frontend)
   + add cratetypeCount to cratetype model. (backend)

**Comment by rweisse** [comment]
These changes are enhancements that doesn't have any impact on sizetypes, products, transfer and transaction data. This will be fixed in near future.

**Comment by fmalcher** [comment]
Great! I think this solves what I addressed in those two issues. :-)

**Comment by fmalcher** [comment]
Do you think this was fully resolved? @rweisse

**Comment by rweisse** [comment]
I hope so.
