### ISSUE TITLE
Wrong inventory data for some events

### ISSUE THREAD

**Issue by fmalcher** [hftlclub/node-iltis#46]
Some events show wrong inventory data

<img width="1122" alt="bildschirmfoto 2017-11-29 um 20 13 56" src="https://user-images.githubusercontent.com/1683147/33394185-d82f878e-d541-11e7-9488-52b5a3dcfba8.png">

**Comment by rweisse** [comment]
I have tried to reproduce this and had "no luck". It seems to work now. I think this bug has been fixed by chance with https://github.com/hftlclub/node-iltis/commit/637e143e1e0a4b30df79607b58956c75c3db6d3f
